stages:
  get_data:
    cmd: python src/get_data.py
    deps:
    - src/get_data.py
    outs:
    - smsspamcollection
  text_preprocessing:
    cmd: python src/text_preprocessing.py
    deps:
    - src/text_preprocessing.py
